keys:
  - &users:
    - &alan 111D6C0637278F94E3438D9B6B2B471B33BC4E0B
  - &hosts:
    - &ein age149y8wcpghrd8zp3tq3ddtu5cjrhqxr8m4sk2fcalclzefmlj59kqt4puzt

creation_rules:
  - path_regex: hosts/ein/secrets.ya?ml$
    key_groups:
      - age:
          - *ein
        pgp:
          - *alan
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *ein
        pgp:
          - *alan
