---
- name: alanp.me - remember compose definition
  set_fact:
    alanp_definition:
      version: '3.8'
      services:
        website:
          image: alanp:latest
          restart: unless-stopped
          ports:
            - "8081:9090"
          environment:
            - "DEV=true"
        whoami:
          image: traefik/whoami
          labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`alanp.me`)"

- name: alanp.me - start compose
  docker_compose:
    project_name: alanp
    recreate: always
    restarted: yes
    remove_orphans: yes
    state: present
    definition: '{{alanp_definition}}'
