---
- name: alanp.me - remember compose definition
  set_fact:
    alanp_definition:
      version: '3.8'
      networks:
        traefik:
          external: true
      services:
        website:
          image: alanp:latest
          networks:
            - traefik
          restart: unless-stopped
          environment:
            - "DEV=true"
          labels:
            traefik.enable: true
            traefik.docker.network: traefik
            traefik.http.routers.alanp.rule: 'Host(`alanp.me`)'
            traefik.http.services.alanp.loadbalancer.server.port: '9090'
            traefik.http.routers.alanp.service: 'alanp'
- name: alanp.me - start compose
  docker_compose:
    project_name: alanp
    recreate: always
    build: yes
    restarted: yes
    remove_orphans: yes
    state: present
    definition: '{{alanp_definition}}'
