---
- name: Start drone docker compose
  docker_compose:
    project_name: drone
    definition:
      version: '3.8'
      services:
        server:
          image: drone/drone:2
          restart: always
          ports:
            - "8080:80"
          volumes:
            - /var/lib/drone:/var/lib/drone/
          environment:
            - DRONE_SERVER_HOST={{ drone.server_name }}
            - DRONE_SERVER_PROTO=https

            - DRONE_RPC_SECRET={{ drone.rpc_secret }}
            - DRONE_USER_CREATE=username:{{ drone.admin_user }},admin:true

            - DRONE_GITHUB_CLIENT_ID={{ drone.github.id }}
            - DRONE_GITHUB_CLIENT_SECRET={{ drone.github.secret }}
        docker-runner:
          image: drone/drone-runner-docker:1
          restart: always
          command: agent
          depends_on:
            - server
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          environment:
            - DRONE_RPC_HOST={{ drone.server_name }}
            - DRONE_RPC_PROTO=https
            - DRONE_RPC_SECRET={{ drone.rpc_secret }}